# typst.toml
[package]
name = "careercraft"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["D.Knafelj <dominik@knafel.io>"]
license = "MIT"
description = "Templates for crafting professional cover letters and resumes in US and German (DIN 5008) formats. The resume template is inspired by Stephen Xu's basic-typst-resume-template."
repository = "https://github.com/dknafelj/careercraft"
keywords = ["cover-letter", "resume", "job-application", "US", "Germany", "DIN5008", "ATS-friendly"]